[package]
name = "getting_started_piston"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.40.0"
pistoncore-glutin_window = "0.69.0"
piston2d-opengl_graphics = "0.78.0"

